function [CP,CU,CV,CC,CN,F4] = BuildC(n,dz,Pe,Sl,Ss,Sr,es,c,u,v,s,dt,cp,k1,Ss1,Ss2)
% This function builds the Jacobian block matrix for the C-equation
% n is the number of grid nodes
% dz is the grid size
% Pe is the Peclet number
% Sl is the leaf source, nondimensional
% Ss is the total stem sink, nondimensional
% Sr is the root sink, nondimensional
% es is the aspect ratio
% c is the nondimensional concentration, nx1
% u is the nondimensional axial velocity, (n-1)x1
% v is the nondimensional radial velocity, nx1
% s is a case number, 0 == steady state, 1 == transient
% dt is the nondimensional time step
% cp is the nondimensional concentration at previous time, nx1
% k1 is a case number, 0 == 'CS', 1 == 'LSb', 2 == 'LSt', 3 == 'LGSb', 4 == 'LGSt'
% Ss1 and Ss2 are the respiration (fr) and growth (fg) sink, nondimensional
% CP is the Jacobian block matrix of size nxn for the P-variable
% CU is the Jacobian block matrix of size nx(n-1) for the U-variable
% CV is the Jacobian block matrix of size nxn for the V-variable
% CC is the Jacobian block matrix of size nxn for the C-variable
% CN is the Jacobian block matrix of size nxn for the Nu-variable
% F4 is the equality (residual) of the C-equation

% P variable       
CP = zeros(n);

% Nu variable
CN = zeros(n);

switch k1
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Constant sink %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    case 0
        % U variable
        a1        = ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*c(1:n-1)./dz ...
                  - (2/210)*((Pe/dz)^2).*u.*(c(2:n) - c(1:n-1)) ...
                  - (1/60)*(Ss/es)*(Pe^2)/dz;
        a2        = - ( Pe - (77/30)*(Pe^2).*v(1:n-2) ).*c(1:n-2)./dz ...
                  + (2/210)*((Pe/dz)^2).*u(1:n-2).*(c(2:n-1) - c(1:n-2)) ...
                  + (1/60)*(Ss/es)*(Pe^2)/dz;
        CU        = diag(a1) + diag(a2,-1);
        CU        = [CU; zeros(1,n-1)];
        CU(n,n-1) =  - ( Pe - (77/30)*(Pe^2).*v(n-1) ).*c(n-1)/dz ...
                  + (2/210)*((Pe/dz)^2).*u(n-1).*(c(n) - c(n-1)) ...
                  + (1/60)*(Ss/es)*(Pe^2)/dz;
        % V variable
        a3        = - (77/30)*(Pe^2).*u(1:n-1).*c(1:n-1)./dz;
        a4        = (77/30)*(Pe^2).*u(1:n-2).*c(1:n-2)./dz;
        CV        = diag(a3) + diag(a4,-1);
        CV        = [CV; zeros(1,n-1)];
        CV        = [CV, zeros(n,1)];
        CV(n,n-1) = (77/30)*(Pe^2).*u(n-1).*c(n-1)./dz; 

        switch s
            case 1
                 % C variable
                 diagC  = 1/dt + ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = 1/dt + Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = 1/dt + ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (c(2:n-1) - cp(2:n-1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + ( (Pe*dz/es).*(2:n-1)' - (1/60)*(Pe^2).*u(2:n-1)./es ).*Ss./dz...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - ( (Pe*dz/es).*(1:n-2)' - (1/60)*(Pe^2).*u(1:n-2)./es ).*Ss./dz;
                 F41    = (c(1) - cp(1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + ( (Pe*dz/es) - (1/60)*(Pe^2).*u(1)./es ).*Ss./dz...
                        - Pe*Sl/dz;
                 F42    = (c(n) - cp(n))./dt ...
                        + (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - ( (Pe*dz/es).*(n-1) - (1/60)*(Pe^2).*u(n-1)./es ).*Ss./dz;
                 F4     = [F41; F4; F42];
                 

            case 0
                % C variable
                 diagC  = ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + ( (Pe*dz/es).*(2:n-1)' - (1/60)*(Pe^2).*u(2:n-1)./es ).*Ss./dz...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - ( (Pe*dz/es).*(1:n-2)' - (1/60)*(Pe^2).*u(1:n-2)./es ).*Ss./dz;
                 F41    = Pe.*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + ( (Pe*dz/es) - (1/60)*(Pe^2).*u(1)./es ).*Ss./dz...
                        - Pe*Sl/dz;
                 F42    = (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - ( (Pe*dz/es).*(n-1) - (1/60)*(Pe^2).*u(n-1)./es ).*Ss./dz;
                 % F42 = 0; %%%%%%%%%% cts c at n
                 F4     = [F41; F4; F42];

        end





%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% linear sink Highest at bottom %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    case 1
        % U variable
        a1        = ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*c(1:n-1)./dz ...
                  - (2/210)*((Pe/dz)^2).*u.*(c(2:n) - c(1:n-1)) ...
                  - 2*(1/60)*(Ss/es)*(Pe^2)*dz.*((1:n-1)')/dz;
        a2        = - ( Pe - (77/30)*(Pe^2).*v(1:n-2) ).*c(1:n-2)./dz ...
                  + (2/210)*((Pe/dz)^2).*u(1:n-2).*(c(2:n-1) - c(1:n-2)) ...
                  + 2*(1/60)*(Ss/es)*(Pe^2)*dz.*((1:n-2)')/dz;
        CU        = diag(a1) + diag(a2,-1);
        CU        = [CU; zeros(1,n-1)];
        CU(n,n-1) =  - ( Pe - (77/30)*(Pe^2).*v(n-1) ).*c(n-1)/dz ...
                  + (2/210)*((Pe/dz)^2).*u(n-1).*(c(n) - c(n-1)) ...
                  + 2*(1/60)*(Ss/es)*(Pe^2)*dz*(n-1)/dz;
        % V variable
        a3        = - (77/30)*(Pe^2).*u(1:n-1).*c(1:n-1)./dz;
        a4        = (77/30)*(Pe^2).*u(1:n-2).*c(1:n-2)./dz;
        CV        = diag(a3) + diag(a4,-1);
        CV        = [CV; zeros(1,n-1)];
        CV        = [CV, zeros(n,1)];
        CV(n,n-1) = (77/30)*(Pe^2).*u(n-1).*c(n-1)./dz;


        switch s
            case 1
                 % C variable
                 diagC  = 1/dt + ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = 1/dt + Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = 1/dt + ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (c(2:n-1) - cp(2:n-1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + 2.*( (Pe*(dz^2)/(2*es)).*((2:n-1)'.^2) ...
                        - (1/60)*(Pe^2)*dz.*u(2:n-1).*((2:n-1)')./es ).*Ss./dz...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - 2.*( (Pe*(dz^2)/(2*es)).*((1:n-2)'.^2) ...
                        - (1/60)*(Pe^2)*dz.*u(1:n-2).*((1:n-2)')./es ).*Ss./dz;
                 F41    = (c(1) - cp(1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + 2*( (Pe*(dz^2)/(2*es)) - (1/60)*(Pe^2)*dz.*u(1)./es ).*Ss./dz...
                        - Pe*Sl/dz;
                 F42    = (c(n) - cp(n))./dt ...
                        + (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - 2*( (Pe*(dz^2)/(2*es)).*((n-1)^2) ...
                        - (1/60)*(Pe^2)*dz.*u(n-1)*(n-1)./es ).*Ss./dz;
                 F4     = [F41; F4; F42];


            case 0
                % C variable
                 diagC  = ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + 2.*( (Pe*(dz^2)/(2*es)).*((2:n-1)'.^2) ...
                        - (1/60)*(Pe^2)*dz.*u(2:n-1).*((2:n-1)')./es ).*Ss./dz...
                        - (Pe - (7/45)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - 2.*( (Pe*(dz^2)/(2*es)).*((1:n-2)'.^2) ...
                        - (1/60)*(Pe^2)*dz.*u(1:n-2).*((1:n-2)')./es ).*Ss./dz;
                 F41    = (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + 2*( (Pe*(dz^2)/(2*es)) - (1/60)*(Pe^2)*dz.*u(1)./es ).*Ss./dz...
                        - Pe*Sl/dz;
                 F42    = (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - 2*( (Pe*(dz^2)/(2*es)).*((n-1)^2) ...
                        - (1/60)*(Pe^2)*dz.*u(n-1)*(n-1)./es ).*Ss./dz;
                 F4     = [F41; F4; F42];
        end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% linear sink Highest at top %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    case 2
        % U variable
        a1        = ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*c(1:n-1)./dz ...
                  - (2/210)*((Pe/dz)^2).*u.*(c(2:n) - c(1:n-1)) ...
                  - 2*(1/60)*(Ss/es)*(Pe^2).*(1 - dz.*(1:n-1)')/dz;
        a2        = - ( Pe - (77/30)*(Pe^2).*v(1:n-2) ).*c(1:n-2)./dz ...
                  + (2/210)*((Pe/dz)^2).*u(1:n-2).*(c(2:n-1) - c(1:n-2)) ...
                  + 2*(1/60)*(Ss/es)*(Pe^2).*(1 - dz.*(1:n-2)')/dz;
        CU        = diag(a1) + diag(a2,-1);
        CU        = [CU; zeros(1,n-1)];
        CU(n,n-1) =  - ( Pe - (77/30)*(Pe^2).*v(n-1) ).*c(n-1)/dz ...
                  + (2/210)*((Pe/dz)^2).*u(n-1).*(c(n) - c(n-1)) ...
                  + 2*(1/60)*(Ss/es)*(1 - dz*(n-1))*(Pe^2)/dz;  
        % V variable
        a3        = - (77/30)*(Pe^2).*u(1:n-1).*c(1:n-1)./dz;
        a4        = (77/30)*(Pe^2).*u(1:n-2).*c(1:n-2)./dz;
        CV        = diag(a3) + diag(a4,-1);
        CV        = [CV; zeros(1,n-1)];
        CV        = [CV, zeros(n,1)];
        CV(n,n-1) = (77/30)*(Pe^2).*u(n-1).*c(n-1)./dz;

        switch s
            case 1
                 % C variable
                 diagC  = 1/dt + ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = 1/dt + Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = 1/dt + ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (c(2:n-1) - cp(2:n-1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + 2.*( (Pe*dz/es).*((2:n-1)').*(1 - dz.*((2:n-1)')./2) ...
                        - (1/60)*(Pe^2).*u(2:n-1).*(1 - dz.*(2:n-1)')./es ).*Ss./dz...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - 2.*( (Pe*dz/es).*((1:n-2)').*(1 - dz.*(1:n-2)'./2) ...
                        - (1/60)*(Pe^2).*u(1:n-2).*(1 - dz.*(1:n-2)')./es ).*Ss./dz;
                 F41    = (c(1) - cp(1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + 2*( (Pe*dz/es)*(1 - dz/2) - (1/60)*(Pe^2).*u(1)*(1 - dz)./es ).*Ss./dz...
                        - Pe*Sl/dz;
                 F42    = (c(n) - cp(n))./dt ...
                        + (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - 2*( (Pe*dz/es)*(n-1)*(1 - dz*(n-1)/2) ...
                        - (1/60)*(Pe^2).*u(n-1)*(1 - dz*(n-1))./es ).*Ss./dz;
                 F4     = [F41; F4; F42];

            case 0
                % C variable
                 diagC  = ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + 2.*( (Pe*dz/es).*((2:n-1)').*(1 - dz.*((2:n-1)')./2) ...
                        - (1/60)*(Pe^2).*u(2:n-1).*(1 - dz.*(2:n-1)')./es ).*Ss./dz...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - 2.*( (Pe*dz/es).*((1:n-2)').*(1 - dz.*(1:n-2)'./2) ...
                        - (1/60)*(Pe^2).*u(1:n-2).*(1 - dz.*(1:n-2)')./es ).*Ss./dz;
                 F41    = (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + 2*( (Pe*dz/es)*(1 - dz/2) - (1/60)*(Pe^2).*u(1)*(1 - dz)./es ).*Ss./dz...
                        - Pe*Sl/dz;
                 F42    = (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - 2*( (Pe*dz/es)*(n-1)*(1 - dz*(n-1)/2) ...
                        - (1/60)*(Pe^2).*u(n-1)*(1 - dz*(n-1))./es ).*Ss./dz;
                 F4     = [F41; F4; F42];
        end

%%%%%%%%%%%%%%%%%%%%%%%%% cts respiration and linear growth highest at top %%%%%%%%%%%%%%%%%%%%%%%%
    case 3
        % U variable
        a1        = ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*c(1:n-1)./dz ...
                  - (2/210)*((Pe/dz)^2).*u.*(c(2:n) - c(1:n-1)) ...
                  - 2.*(1/60)*(Ss2/es)*(Pe^2).*( dz.*(1:n-1)')./dz ...
                  + (1/60)*(Ss1/es)*(Pe^2)/dz;
        a2        = - ( Pe - (77/30)*(Pe^2).*v(1:n-2) ).*c(1:n-2)./dz ...
                  + (2/210)*((Pe/dz)^2).*u(1:n-2).*(c(2:n-1) - c(1:n-2)) ...
                  + 2.*(1/60)*(Ss2/es)*(Pe^2).*( dz.*(1:n-2)')./dz ...
                  + (1/60)*(Ss1/es)*(Pe^2)/dz;
        CU        = diag(a1) + diag(a2,-1);
        CU        = [CU; zeros(1,n-1)];
        CU(n,n-1) =  - ( Pe - (77/30)*(Pe^2).*v(n-1) ).*c(n-1)/dz ...
                  + (2/210)*((Pe/dz)^2).*u(n-1).*(c(n) - c(n-1)) ...
                  + 2.*(1/60)*(Ss2/es)*(Pe^2).*(dz.*(n-1))/dz ...
                  + (1/60)*(Ss1/es)*(Pe^2)/dz;   
        % V variable
        a3        = - (77/30)*(Pe^2).*u(1:n-1).*c(1:n-1)./dz;
        a4        = (77/30)*(Pe^2).*u(1:n-2).*c(1:n-2)./dz;
        CV        = diag(a3) + diag(a4,-1);
        CV        = [CV; zeros(1,n-1)];
        CV        = [CV, zeros(n,1)];
        CV(n,n-1) = (77/30)*(Pe^2).*u(n-1).*c(n-1)./dz;   

        switch s
            case 1
                 % C variable
                 diagC  = 1/dt + ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = 1/dt + Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = 1/dt + ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (c(2:n-1) - cp(2:n-1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + ( (Pe*dz/es).*((2:n-1)') - (1/60)*( (Pe^2)/es ).*u(2:n-1) ).*Ss1./dz ...
                        + ( (Pe*(dz^2)/es).*((2:n-1)'.^2) - 2*(1/60)*( (Pe^2)/es )*dz.*u(2:n-1).*((2:n-1)') ).*Ss2./dz ...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - ( (Pe*dz/es).*((1:n-2)') - (1/60)*( (Pe^2)/es ).*u(1:n-2) ).*Ss1./dz ...
                        - ( (Pe*(dz^2)/es).*((1:n-2)'.^2) - 2*(1/60)*( (Pe^2)/es )*dz.*u(1:n-2).*((1:n-2)') ).*Ss2./dz;
                 F41    = (c(1) - cp(1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + ( (Pe*dz/es) - (1/60)*( (Pe^2)/es ).*u(1) ).*Ss1/dz ...
                        + ( (Pe*(dz^2)/es) - 2*(1/60)*( (Pe^2)/es )*dz.*u(1) )*Ss2/dz ...
                        - Pe*Sl/dz;
                 F42    = (c(n) - cp(n))./dt ...
                        + (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - ( (Pe*dz/es).*((n-1)) - (1/60)*( (Pe^2)/es ).*u(n-1) ).*Ss1/dz ...
                        - ( (Pe*(dz^2)/es).*((n-1).^2) - 2*(1/60)*( (Pe^2)/es )*dz.*u(n-1).*((n-1)) ).*Ss2/dz;
                 F4     = [F41; F4; F42];

            case 0
                % C variable
                 diagC  = ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);
 
                 % Equality
                 F4     = (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + ( (Pe*dz/es).*((2:n-1)') - (1/60)*( (Pe^2)/es ).*u(2:n-1) ).*Ss1/dz ...
                        + ( (Pe*(dz^2)/es).*((2:n-1)'.^2) - 2*(1/60)*( (Pe^2)/es )*dz.*u(2:n-1).*((2:n-1)') ).*Ss2/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - ( (Pe*dz/es).*((1:n-2)') - (1/60)*( (Pe^2)/es ).*u(1:n-2) ).*Ss1/dz ...
                        - ( (Pe*(dz^2)/es).*((1:n-2)'.^2) - 2*(1/60)*( (Pe^2)/es )*dz.*u(1:n-2).*((1:n-2)') ).*Ss2/dz;
                 F41    = (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + ( (Pe*dz/es) - (1/60)*( (Pe^2)/es ).*u(1) ).*Ss1/dz ...
                        + ( (Pe*(dz^2)/es) - 2*(1/60)*( (Pe^2)/es )*dz.*u(1) ).*Ss2/dz ...
                        - Pe*Sl/dz;
                 F42    = (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2)*v(n-1))*u(n-1)*c(n-1)/dz...
                        + ( (1/210)*(Pe^2)*(u(n-1)^2) + es^2 )*(c(n) - c(n-1))/(dz^2)...
                        - ( (Pe*dz/es).*((n-1)) - (1/60)*( (Pe^2)/es )*u(n-1) ).*Ss1/dz ...
                        - ( (Pe*(dz^2)/es).*((n-1)^2) - 2*(1/60)*( (Pe^2)/es )*dz*u(n-1)*((n-1)) ).*Ss2/dz;
                 F4     = [F41; F4; F42];
        end
              
%%%%%%%%%%%%%%%%%%%%%%%%% cts respiration and linear growth highest at botttom %%%%%%%%%%%%%%%%%%%%%%%%
    case 4
        % U variable
        a1        = ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*c(1:n-1)./dz ...
                  - (2/2101)*((Pe/dz)^2).*u.*(c(2:n) - c(1:n-1)) ...
                  - 2.*(1/60)*(Ss2/es)*(Pe^2).*( 1 - dz.*(1:n-1)' )/dz ...
                  + (1/60)*(Ss1/es)*(Pe^2)/dz;
        a2        = - ( Pe - (77/30)*(Pe^2).*v(1:n-2) ).*c(1:n-2)./dz ...
                  + (2/210)*((Pe/dz)^2).*u(1:n-2).*(c(2:n-1) - c(1:n-2)) ...
                  + 2.*(1/60)*(Ss2/es)*(Pe^2).*(1 - dz.*(1:n-2)')/dz ...
                  + (1/60)*(Ss1/es)*(Pe^2)/dz;
        CU        = diag(a1) + diag(a2,-1);
        CU        = [CU; zeros(1,n-1)];
        CU(n,n-1) =  - ( Pe - (77/30)*(Pe^2).*v(n-1) ).*c(n-1)/dz ...
                  + (2/210)*((Pe/dz)^2).*u(n-1).*(c(n) - c(n-1)) ...
                  + 2.*(1/60)*(Ss2/es)*(Pe^2).*(1 - dz.*(n-1))/dz ...
                  + (1/60)*(Ss1/es)*(Pe^2)/dz;   
        % V variable
        a3        = - (77/30)*(Pe^2).*u(1:n-1).*c(1:n-1)./dz;
        a4        = (77/30)*(Pe^2).*u(1:n-2).*c(1:n-2)./dz;
        CV        = diag(a3) + diag(a4,-1);
        CV        = [CV; zeros(1,n-1)];
        CV        = [CV, zeros(n,1)];
        CV(n,n-1) = (77/30)*(Pe^2).*u(n-1).*c(n-1)./dz;  

        switch s
            case 1
                 % C variable
                 diagC  = 1/dt + ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = 1/dt + Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = 1/dt + ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);

                 % Equality
                 F4     = (c(2:n-1) - cp(2:n-1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + ( (Pe*dz/es).*((2:n-1)') - (1/60)*( (Pe^2)/es ).*u(2:n-1) ).*Ss1 ...
                        + 2.*( (Pe*dz/es).*((2:n-1)').*(1 - dz.*((2:n-1)')./2) ...
                        - (1/60)*(Pe^2).*u(2:n-1).*(1 - dz.*(2:n-1)')./es ).*Ss2./dz ...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - ( (Pe*dz/es).*((1:n-2)') - (1/60)*( (Pe^2)/es ).*u(1:n-2) ).*Ss1 ...
                        - 2.*( (Pe*dz/es).*((1:n-2)').*(1 - dz.*(1:n-2)'./2) ...
                        - (1/60)*(Pe^2).*u(1:n-2).*(1 - dz.*(1:n-2)')./es ).*Ss2./dz;

                 F41    = (c(1) - cp(1))./dt ...
                        + (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/2100)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + ( (Pe*dz/es) - (1/60)*( (Pe^2)/es ).*u(1) ).*Ss1 ...
                        + 2.*( (Pe*dz/es)*(1 - dz/2) - (1/60)*(Pe^2).*u(1).*(1 - dz)./es ).*Ss2./dz ...
                        - Pe*Sl/dz;
                 F42    = (c(n) - cp(n))./dt ...
                        + (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - ( (Pe*dz/es).*((n-1)) - (1/60)*( (Pe^2)/es ).*u(n-1) ).*Ss1 ...
                        - 2.*( (Pe*dz/es).*((n-1)).*(1 - dz*(n-1)/2) ...
                        - (1/60)*(Pe^2).*u(n-1).*(1 - dz.*(n-1))./es ).*Ss2./dz;
                 F4     = [F41; F4; F42];

            case 0
                % C variable
                 diagC  = ( Pe - (77/30)*(Pe^2).*v(2:n-1) ).*u(2:n-1)./dz ...
                        + ( (1/210)*(Pe^2).*( u(2:n-1).^2 ) + es^2 )./(dz^2)...
                        + ( (1/210)*(Pe^2).*( u(1:n-2).^2 ) + es^2 )./(dz^2);
                 diagC1 = Pe*u(1)/dz ...
                        + ( (1/210)*(Pe^2).*( u(1).^2 ) + es^2 )./(dz^2);
                 diagC2 = ( (1/210)*(Pe^2).*( u(n-1).^2 ) + es^2 )./(dz^2);
                 diagC  = [diagC1; diagC; diagC2];
                 uppC   = - ( (1/210)*(Pe^2).*( u(1:n-1).^2 ) + es^2 )./(dz^2);
                 lowC   = - ( Pe - (77/30)*(Pe^2).*v(1:n-1) ).*u./dz ...
                        - ( (1/210)*(Pe^2).*( u.^2 ) + es^2 )./(dz^2);
                 CC     = diag(diagC) + diag(uppC,1) + diag(lowC,-1);
                 
                 % Equality
                 F4     = (Pe - (77/30)*(Pe^2).*v(2:n-1)).*u(2:n-1).*c(2:n-1)./dz...
                        - ( (1/210)*(Pe^2).*(u(2:n-1).^2) + es^2 ).*(c(3:n) - c(2:n-1))./(dz^2)...
                        + ( (Pe*dz/es).*((2:n-1)') - (1/60)*( (Pe^2)/es ).*u(2:n-1) ).*Ss1 ...
                        + 2.*( (Pe*dz/es).*((2:n-1)').*(1 - dz.*((2:n-1)')./2) ...
                        - (1/60)*(Pe^2).*u(2:n-1).*(1 - dz.*(2:n-1)')./es ).*Ss2./dz ...
                        - (Pe - (77/30)*(Pe^2).*v(1:n-2)).*u(1:n-2).*c(1:n-2)./dz...
                        + ( (1/210)*(Pe^2).*(u(1:n-2).^2) + es^2 ).*(c(2:n-1) - c(1:n-2))./(dz^2)...
                        - ( (Pe*dz/es).*((1:n-2)') - (1/60)*( (Pe^2)/es ).*u(1:n-2) ).*Ss1 ...
                        - 2.*( (Pe*dz/es).*((1:n-2)').*(1 - dz.*(1:n-2)'./2) ...
                        - (1/60)*(Pe^2).*u(1:n-2).*(1 - dz.*(1:n-2)')./es ).*Ss2./dz;

                 F41    = (Pe - (77/30)*(Pe^2).*v(1)).*u(1).*c(1)./dz...
                        - ( (1/210)*(Pe^2).*(u(1).^2) + es^2 ).*(c(2) - c(1))./(dz^2)...
                        + ( (Pe*dz/es) - (1/60)*( (Pe^2)/es ).*u(1) ).*Ss1 ...
                        + 2.*( (Pe*dz/es)*(1 - dz/2) - (1/60)*(Pe^2).*u(1).*(1 - dz)./es ).*Ss2./dz ...
                        - Pe*Sl/dz;
                 F42    = (Pe*Sr + (Pe/es)*Ss)/dz ...
                        - (Pe - (77/30)*(Pe^2).*v(n-1)).*u(n-1).*c(n-1)./dz...
                        + ( (1/210)*(Pe^2).*(u(n-1).^2) + es^2 ).*(c(n) - c(n-1))./(dz^2)...
                        - ( (Pe*dz/es).*((n-1)) - (1/60)*( (Pe^2)/es ).*u(n-1) ).*Ss1 ...
                        - 2.*( (Pe*dz/es).*((n-1)).*(1 - dz*(n-1)/2) ...
                        - (1/60)*(Pe^2).*u(n-1).*(1 - dz.*(n-1))./es ).*Ss2./dz;
                 F4     = [F41; F4; F42];
        end

end



end
